language: ruby
rvm:
  - 2.6

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

bundler_args: --without development staging production

before_install:
  - gem update --system
  - gem install bundler

install:
  - bundle install
  - nvm install
  - npm i -g yarn

before_script:
  - "./bin/setup"
  - "bundle exec rake db:setup"
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
  - "chmod +x ./cc-test-reporter"
  - "./cc-test-reporter before-build"

script:
  - "bundle exec rails assets:precompile"
  - "bundle exec rails test test/*"
  - "yarn test"

after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"

services:
  - postgresql

addons:
  postgresql: "9.6"
  chrome: stable
