name: build, test and deploy test environment on pr

on:
  pull_request:
    branches:
    - main

  push:
    branches:
    - build_test_deploy

jobs:
  
  build_and_test:
    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2

      - name: Set image tag
        run: |
          SHORT_SHA=$(git describe --always)
          echo "ghcr.io/internetee/auction_center:RC_$SHORT_SHA" > TAG

      - name: Set config files for build
        run: |
          cp config/database.yml.sample config/database.yml
          ls -l config/

      - name: Build image
        run: |
          docker build -t $(cat TAG) -f Dockerfile.generic .
          docker images

      - name: Push Docker image to gh container registry
        env:
          PASSWORD: ${{ secrets.GHCR_PAT }}
        run: |
          echo $PASSWORD | docker login -u internetee --password-stdin
          docker push $(cat TAG)
